_G.Signal = require("./classes/signal")
_G.Color3 = require("./classes/color")
_G.Vector3 = require("./classes/vector3")
_G.CFrame = require("./classes/cframe")
_G.Vector2 = require("./classes/vector2")
